### ISSUE TITLE
Text lose

### ISSUE THREAD

**Issue by JasonkayZK** [srwiley/rasterx#10]
I tried to convert a svg which contains words in <textPath>, but lose all text after convertion?
origin svg:

![in](https://user-images.githubusercontent.com/40811521/103328505-1b62b100-4a94-11eb-837d-86eedb2f940a.png)

after:

![out](https://user-images.githubusercontent.com/40811521/103328519-274e7300-4a94-11eb-9a3e-0500d58706f6.png)

**Comment by srwiley** [comment]
Hi  JasonkayZK,

Thank you for your interest in rasterx and oksvg. 

Yes, text is not supported by oksvg. If you take a look at the supported and not supported tags in the SVG docs, [SVG_Element_List.txt](https://github.com/srwiley/oksvg/blob/master/doc/SVG_Element_List.txt), you will see that text tags are not supported. It you are willing to submit a pull request with testing and modifications that makes text tags work, then I will certainly give it full consideration. Until then I will close this issue.
