### ISSUE TITLE
Dashes = [0,0] ends up in infinite loop

### ISSUE THREAD

**Issue by rcoreilly** [srwiley/rasterx#4]
if you scale down lines with dashes to a sufficiently small size, the fixed.Int26_6 version can end up being 0, at which point the Dasher rendering code in dash.go ends up stuck in an infinite loop!

Best soln would be to fix SetStroke to detect the problem and reset Dashes if all are 0.

I'm now catching this upstream, but would be good to fix here too.

**Comment by srwiley** [comment]
Good call Randy. If any one of the dash spaces is greater than zero it will work, so I put in a test in SetStroke to see if any of the dashes are positive. If none are, then it ignores the dashes. Plus I make it a little more idiomatic. Please get back to me if there is any problem.
